name: Deploy MkDocs site

on:
  push:
    branches: [main]  # اگر برنچ پیش‌فرض چیز دیگه‌ایه، تغییرش بده

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .  # چون mkdocs.yml در همین پوشه است

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
